apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-web
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videos-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: videos-web
    spec:
      containers:
      - name: videos-web-container
        image: oumaymacharrad/videos-webapp:1.0.10@sha256:e153ee966ffdb5e4b44c9e54ea8992664de5b1133cce520b023f502c743f93be 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "125m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
        envFrom:
            - configMapRef:
                name: frontend-env
        securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault


