apiVersion: v1
kind: ConfigMap
metadata:
  name: playlist-env
  namespace: microservices
data:
  ENVIRONMENT: DEBUG
  REDIS_HOST: videowebapp.redis.cache.windows.net
  REDIS_PORT: "6379"
  VIDEOS_API_HOST: videos-api
  VIDEOS_API_PORT: "10010"
  JAEGER_ENDPOINT: http://jaeger-collector.jaeger:14268/api/traces

