apiVersion: v1
kind: Service
metadata:
  name: playlist-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 10010
      targetPort: 10010
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: playlist-api

