apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-api
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videos-api
  template:
    metadata:
      labels:
        app: videos-api
    spec:
      initContainers:
        - name: data-seed
          image: oumaymacharrad/data-seed-job:1.0.19@sha256:9ebb42c86a8e492decc9d285e2622e77677f4b16d6d1b8ba20218416075224e4
          envFrom:
            - configMapRef:
                name: data-seed-env
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playlist-api-secret
                  key: PASSWORD
      containers:
        - name: videos-api-container
          image: oumaymacharrad/videos-microservice:1.0.8@sha256:26125a3d632cb52b400813f1aab12f1c2cf1e4748f78ece8a197db9889650957 
          ports:
            - containerPort: 10010
            - containerPort: 8000
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 10010
          livenessProbe:
            httpGet:
              path: /
              port: 10010
          envFrom:
            - configMapRef:
                name: videos-env
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playlist-api-secret
                  key: PASSWORD

